### ISSUE TITLE
inference seems to take way more memory

### ISSUE THREAD

**Issue by Borda** [Huage001/PaintTransformer#5]
Hi, I wanted to try to play with so I cloned it locally and run inference but seems I can't fit GPU memory even it shall be fine as the model askes for 3.5GB and I have RTX 2070 with 8GB memory which is completely free...
```
python inference.py
Traceback (most recent call last):
  File "inference.py", line 490, in <module>
    main(input_path='input/chicago.jpg',
  File "inference.py", line 445, in main
    final_result = param2img_parallel(param, decision, meta_brushes, final_result)
  File "inference.py", line 263, in param2img_parallel
    valid_foregrounds, valid_alphas = param2stroke(param[decision, :], patch_size_y, patch_size_x, meta_brushes)
  File "inference.py", line 74, in param2stroke
    foreground = morphology.dilation(foreground)
  File "/home/jirka/Workingspace/PaintTransformer/inference/morphology.py", line 49, in dilation
    channel = nn.functional.unfold(x_pad, 2 * m + 1, padding=0, stride=1).view(b, c, -1, h, w)
  File "/home/jirka/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 4472, in unfold
    return torch._C._nn.im2col(input, _pair(kernel_size), _pair(dilation), _pair(padding), _pair(stride))
RuntimeError: CUDA out of memory. Tried to allocate 3.38 GiB (GPU 0; 7.80 GiB total capacity; 3.39 GiB already allocated; 3.25 GiB free; 3.41 GiB reserved in total by PyTorch)
```
well, it seems like it needs to allocate twice the amount, so maybe allow also CPU inference?

**Comment by Huage001** [comment]
Hi,
Thank you for your interest!
Have you tried setting _serial_ parameter in the main function to _True_?

**Comment by Borda** [comment]
not yet, is this option also an argument of the script, such as `python inference.py --serial <image-path>`?

**Comment by Huage001** [comment]
You can change False into True in Line 496 (last line) of inference.py.
We will set it as an argument in the future to make the configuration easier.
